### ISSUE TITLE
Don't use OkHttp’s internal APIs?

### ISSUE THREAD

**Issue by swankjesse** [Babylonpartners/certificate-transparency-android#4]
For example, the CertificateChainCleaner is in our `internal` package and we don't guarantee any API stability in that package across releases. For example, it'll break when you go from OkHttp 3.14 to 4.0.

You should either skip it (certificates from OkHttp are already cleaned) or copy the cleaner code into your own codebase!

**Comment by yschimke** [comment]
I just hit this in testing

**Comment by mattmook** [comment]
@swankjesse how do you get the cleaned certificates from a network interceptor?

As far as could tell, `chain.connection()?.handshake()?.peerCertificates()` is uncleaned, with `CertificateChainCleaner` only being used in the `CertificatePinner` class as far as I could tell looking through the OkHttp sources.

Regardless, it's simple enough for me to replace this code with my own so I will do that.

**Comment by swankjesse** [comment]
@mattmook oh yeah, you're totally right. That's ’cause we don't bother because cleaning ’em is potentially an expensive operation. But that's not a good API for us. Lemme track that as something we should fix.

**Comment by yschimke** [comment]
What is the expected Expect-CT handling when served additional certificates?

**Comment by mattmook** [comment]
As far as I understood there are some scenarios where we require the issuer information from the certificate chain and with that in mind you want a cleaned chain to ensure we get the right information, in order to avoid the similar issues used to defeat early implementations of pinning when directly using `peerCertificates`.

To be fair though I'm going to do some analysis to see if those scenarios actually ever occur in the wild as it may just be code that makes sense in the use cases of `certificate-transparency-java` that some of this code was derived from but wasn't well structured for use on a client.

**Comment by yschimke** [comment]
I was thinking in the opposite direction. CT generally seems like a defense in depth exercise 

CAs when issuing certificates need to do so transparently so companies can monitor those issues in their name. E.g. a hacked or social engineering case. 

Certificates used actively in the wild should be confirmed to be in the log otherwise it’s possible to subvert the above. 

Clients should report breaches instead of just failing. 

Therefore an I cleaned certificate should probably be checked?

Compan

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mattmook** [comment]
It's a flaw that our networking libraries don't provide the actual chain used to verify the certificates in the first place. It's exactly this flaw that lead to earlier versions of OkHttp having a security issue raised when the pinning implementation used `peerCertificates` rather than the cleaned chain - https://www.cvedetails.com/cve/CVE-2016-2402/ which is the reason why we need the CertificateChainCleaner in the first place.

With that in mind, I see a discrepancy in the certificate chain as an independent issue from CT. Clients should perhaps be aware of it but just as they should be when using pinning or nothing as it is an indication that something isn't quite right.

**Comment by yschimke** [comment]
Yep. But at least for reporting the spec declares both uncleaned and cleaned be sent IIUC. served-certificate-chain and validated-certificate-chain

**Comment by yschimke** [comment]
So yep. You need a cleaner. Agreed.

**Comment by yschimke** [comment]
Nice, just saw the commit.  I'm blocked on this in upgrading to 4.0, so I'm happy to test once you have a release version.  Really happy to see this library.

**Comment by mattmook** [comment]
Tagging now. Let me know if you have any problems
